name: CI
on:
  push:
    branches:
      - "main"
  pull_request:
    branches:
      - "main"
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test on ${{ matrix.os }}, Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macOS-latest, ubuntu-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v1

    - name: Additional info about the build
      shell: bash
      run: |
        uname -a
        df -h
        ulimit -a

    - name: Remove uav_analysis from the dependencies
      shell: bash
      run: |
         sed -i -E 's/- --editable.*$/''/' environment-dev.yml

    - uses: conda-incubator/setup-miniconda@v2
      with:
        python-version: ${{ matrix.python-version }}
        environment-file: environment-dev.yml

        channels: conda-forge,defaults

        activate-environment: test
        auto-update-conda: false
        auto-activate-base: false
        show-channel-urls: true

    - name: Install uav_analysis
      shell:  bash -l {0}
      run: |
        git clone https://github.com/symbench/uav-analysis.git
        cd uav-analysis
        python -m pip install -e .


    - name: Install package
      shell: bash -l {0}
      run: |
        python -m pip install -e .
        conda list

    - name: Run tests
      shell: bash -l {0}
      run: |
        pytest -v --color=yes symbench_athens_client/tests/

  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: symbench/symbench-athens-client:latest
          build-args: |
            GITLAB_TOKEN=${{ secrets.GITLAB_TOKEN }}
          file: docker/Dockerfile
